{{- range $component := list "backend" "frontend" "migration" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: card-credit-{{ $component }}
  namespace: {{ $.Release.Namespace }}
automountServiceAccountToken: false
{{- end }}
